AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Stack for creating sertifiseringer webpage
Resources:
  LambdaUploadToS3:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda-upload-to-s3.lambda_handler
      Runtime: nodejs14.x
      CodeUri: s3://eira-code-sam-test/ec0e926e36f228e2ae0b0a8fb2ffa5cf
      MemorySize: 128
      Timeout: 3
      Events:
        UploadEvent:
          Type: HttpApi
          Properties:
            Path: /upload
            Method: PUT
            ApiId:
              Ref: MyHttpApi
  LambdaToDynamoDB:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda-to-dynamodb.lambda_handler
      Runtime: nodejs14.x
      CodeUri: s3://eira-code-sam-test/ec0e926e36f228e2ae0b0a8fb2ffa5cf
      MemorySize: 128
      Timeout: 3
      Events:
        GetEvent:
          Type: HttpApi
          Properties:
            Path: /sertifiseringer
            Method: GET
            ApiId:
              Ref: MyHttpApi
        GetIdEvent:
          Type: HttpApi
          Properties:
            Path: /sertifiseringer/{id}
            Method: GET
            ApiId:
              Ref: MyHttpApi
        PutEvent:
          Type: HttpApi
          Properties:
            Path: /sertifiseringer
            Method: PUT
            ApiId:
              Ref: MyHttpApi
        DeleteEvent:
          Type: HttpApi
          Properties:
            Path: /sertifiseringer/{id}
            Method: DELETE
            ApiId:
              Ref: MyHttpApi
      Policies:
      - DynamoDBCrudPolicy:
          TableName: eira-sertifiseringer-table-sam
  MyHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: test
      CorsConfiguration:
        AllowOrigins:
        - '*'
        AllowHeaders:
        - '*'
        AllowMethods:
        - '*'
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: eira-sertifiseringer-bucket-sam
      WebsiteConfiguration:
        IndexDocument: index.html
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: '2012-10-17'
        Statement:
        - Sid: PublicReadForGetBucketObjects
          Effect: Allow
          Principal: '*'
          Action:
          - s3:GetObject
          - s3:PutObject
          - s3:*
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:s3:::'
              - Ref: MyS3Bucket
              - /*
      Bucket:
        Ref: MyS3Bucket
  MyDynamoDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      PrimaryKey:
        Name: id
        Type: String
      TableName: eira-sertifiseringer-table-sam
